# Generated by Django 4.0.3 on 2022-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tlf', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
