# Generated by Django 4.0.3 on 2022-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='dni',
            field=models.CharField(default='Ninguno', max_length=9),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='tlf',
            field=models.CharField(default='Ninguno', max_length=9),
        ),
    ]
