# Generated by Django 4.0.3 on 2022-03-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_alumnos_dni_alter_alumnos_tlf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
    ]
